[package]
name = "rdp-rs"
version = "0.1.0"
authors = ["citronneur <citronneur@gmail.com>"]

[lib]
name = "rdp"
path = "src/lib.rs"

[[bin]]
name = "rdp-rs-client"
path = "src/bin/client.rs"

[features]
# The reason we do this is because doctests don't get cfg(test)
# See: https://github.com/rust-lang/cargo/issues/4669
integration = []

[dependencies]
native-tls = "^0.2"
byteorder = "^1.3"
bufstream = "0.1"
indexmap = "^1.3"
yasna = { version = "0.3.1", features = ["num-bigint"] }
md4 = "^0.8"
hmac = "^0.7"
md-5 = "^0.8"
rand = "^0.7"
rust-crypto = "^0.2"
num-bigint = "^0.2"
x509-parser = "0.6.5"
winit = "0.22.0"
winapi = "0.3.8"